### ISSUE TITLE
performance improvement of dataset 

### ISSUE THREAD

**Issue by gsoykan** [barisbatuhan/SSuperGAN#3]
Dataset getItem should fetch from  preloaded image data in the form of ndarray

**Comment by caghankoksal** [comment]
Square Panel Coordinates can be stores and also square face coordinates can be stored to increase efficiency.

**Comment by barisbatuhan** [comment]
an image annotation extractor is implemented, processed coordinates for the panel boxes and face boxes are extracted, a dataset object is created that uses these extracted coordinates.
