### ISSUE TITLE
Name of the comic books

### ISSUE THREAD

**Issue by surajsrivathsa** [barisbatuhan/SSuperGAN#32]
Could you let me know if you have the names of the comic books used in the dataset

**Comment by gsoykan** [comment]
Dear @surajsrivathsa we used "Comics" dataset by "The Amazing Mysteries of the Gutter" paper by Iyyer et al. 
Here is the link for their [repo](https://github.com/miyyer/comics). 
Unfortunately, they do not provide the names of the comics.

**Comment by surajsrivathsa** [comment]
Thank you, Will check it out
