### ISSUE TITLE
Problematic Face Annotations

### ISSUE THREAD

**Issue by caghankoksal** [barisbatuhan/SSuperGAN#4]
- Preprocess Face Annotations to cases where aspect ratio is not proper for expected face annotations.
Example :
<img width="381" alt="Screen Shot 2021-05-07 at 09 27 03" src="https://user-images.githubusercontent.com/38569170/117406884-6430e780-af16-11eb-877e-191abcbac66f.png">

Folder - 3769 : 10_5.jpg

<img width="672" alt="Screen Shot 2021-05-07 at 09 32 33" src="https://user-images.githubusercontent.com/38569170/117407394-297b7f00-af17-11eb-91c7-e64a0ae45308.png">

Folder - 34  54_5.jpg

**Comment by caghankoksal** [comment]
Folder - 3769 : 10_5.jpg

**Comment by barisbatuhan** [comment]
with the new golden age panel dataset object, this problem is solved.
